name: rsyncd
description: rsync daemon
version: "1.0.1"
slug: rsyncd
url: "https://github.com/popjelev/hassio-addons/tree/main/rsyncd"
arch:
  - i386
  - amd64
  - armhf
  - armv7
  - aarch64
hassio_api: true
init: false
startup: services
host_network: true
options:
  password: "replace_with_bcrypt_hash_of_password"
  hosts_allow: "0.0.0.0/24"
schema:
  password: str
  hosts_allow: str
map:
  - backup:ro
