#!/usr/bin/env bash
# ==============================================================================
# Start rsyncd service
# ==============================================================================
exec rsync \
	--verbose \
	--daemon \
	--no-detach \
	--config=/etc/rsyncd.conf